### ISSUE TITLE
 ConnectException

### ISSUE THREAD

**Issue by JafferWilson** [angelkurten/PriceBTCAPI#1]
Please check while running the repository, I encountered the following error:
![entirepage error](https://user-images.githubusercontent.com/13446197/33704544-f24c81f0-db52-11e7-9d35-af34776dedbd.png)
https://gist.github.com/JafferWilson/782319ceebd7ca152cc01435e70307ff

**Comment by JafferWilson** [comment]
What I should do?

**Comment by angelkurten** [comment]
Please remove contract Cryptropay in App/Oriana/Oriana.php

![screenshot_1](https://user-images.githubusercontent.com/2807174/33720170-1c3c3e78-db31-11e7-8aa4-09da4d9e4246.png)

**Comment by JafferWilson** [comment]
Thanks it worked... :)
